server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:6542/reg
    username: reg
    password: reg
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
