#server:
#  port: 8082
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#
#    username: postgres
#    password: ваш_пароль
server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: course
    password: course
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true