server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:6541/course
    username: course
    password: course
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect

